# Conda environment file for developers
name: data-panels-dev
channels:
  - defaults
  - conda-forge
  - http://idshost/conda-channels/ids-skyworks
dependencies:
# Packages required for development
  - conda
  - conda-build
  - conda-verify
  # testing
  - pytest=7.1.2
  - pylint=2.14.4
  - mypy == 0.961
  - pre-commit=2.20.0
# Packages required by the user to run it
  - python=3.8
  - pydantic=1.9.1
  - toml=0.10.2
  - numpy=1.23.0
  - pandas=1.4.3
  - matplotlib=3.5.1
  # from IDS-skyworks channel
  - srr=1.0.0 
  #pip-only requirements
  - pip=22.1.2
  - pip:
      - --trusted-host skypypi
      - --extra-index-url http://skypypi/
      - pwdatatools==0.2.1